// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXYg8PScH8gBzUdZuRz9eYVLR35qlVva0',
    appId: '1:193605722032:web:a7d369ce34d2bf1eeac075',
    messagingSenderId: '193605722032',
    projectId: 'secondtry-3e160',
    authDomain: 'secondtry-3e160.firebaseapp.com',
    storageBucket: 'secondtry-3e160.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBELotPdZGoWCIE8Q6PDqzCmxsHjcgN5Y',
    appId: '1:193605722032:android:843b670342a3351aeac075',
    messagingSenderId: '193605722032',
    projectId: 'secondtry-3e160',
    storageBucket: 'secondtry-3e160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnYukjJsSmCtj06nZUzyqoNyTNHlaxtXM',
    appId: '1:193605722032:ios:0dbd5ec9d4b1cf88eac075',
    messagingSenderId: '193605722032',
    projectId: 'secondtry-3e160',
    storageBucket: 'secondtry-3e160.appspot.com',
    iosBundleId: 'com.example.secondtry',
  );
}
